### PR TITLE
 Add Syscalls, and Register and Memory Tabs Documentation

### PR DESCRIPTION
**Pull request by YahyaElgabra**
Description:

This PR includes the first iteration of documentation for the MIPS simulator interface, detailing the Registers and Memory tabs. It also introduces syscall documentation, focusing on syscalls 30 to 42, which handle system time and MIDI operations.

Changes:

Created a basic guide for the Registers and Memory tabs (registers-and-memory.md).
Documented Saturn's MIPS syscalls, covering available syscalls on Satrun (syscalls.md).
The intent is to provide users with the foundational knowledge required for interacting with Saturn and understanding syscalls' functionality. 

Please review the attached documents for accuracy and completeness. Suggestions for further details and potential improvements are welcome.

### CODE REVIEW

**Comment by krishnacheemalapati** [comment]
I noticed in the current documentation that details about registers and memory are a bit sparse. I believe adding more information in these areas would enhance the overall comprehensiveness of the documentation.

Additionally, I experimented with a MIDI syscall, and unfortunately, it took a considerable amount of time to load. I think it's crucial to include this observation in the documentation to give users a heads-up about potential loading delays when utilizing the MIDI syscall.

If you could implement this changes, that would be great Yahya. Let me know if you need me to clarify on anything I mentioned.

**Comment by YahyaElgabra** [comment]
I already noticed the MIDI problem and talked about it with Taylor (the Author) actually, it turns out I misunderstood how the midi system works. I will have to revamp some more parts of it that were not mentioned here

https://github.com/YahyaElgabra/saturn/pull/1

**Comment by krishnacheemalapati** [comment]
Also I realized that you covered syscalls for printing to the system as an example. While I think that's a good idea, we already have documentation covering the different system calls that would allow a developer to interact with the console. I'd recommend using a different example in your syscall section.

**Comment by deonchan2012** [comment]
After taking a look at your documentation, I notice a distinct lack of images for the register and memory tabs.

**Comment by deonchan2012** [comment]
Changes look good and appropriate.

**Pull request merged**
